apiVersion: v1
kind: Pod
metadata:
  name: pytorch-gpu
spec:
  containers:
  - name: pytorch-gpu
    image: "gcr.io/agarwalrohit-sandbox/pytorch-gpu:v0.4.0"
    command: ["python3",  "/matmul.py", "cuda", "200"]
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never
