apiVersion: batch/v1
kind: Job
metadata:
  name: tensorflow-gpu
spec:
  template:
    metadata:
      name: tensorflow-gpu
    spec:
      containers:
      - name: tensorflow-gpu
        image: "gcr.io/agarwalrohit-sandbox/tensorflow-gpu:v0.3"
        command: ["python",  "/matmul.py", "/gpu:0", "20"]
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
