apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-gpu
spec:
  containers:
  - name: tensorflow-gpu
    image: "gcr.io/agarwalrohit-sandbox/tensorflow-gpu:v1.8"
    command: ["python",  "/matmul.py", "/gpu:0", "200"]
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never
