apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: "gcr.io/agarwalrohit-sandbox/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1
