apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-cpu
spec:
  containers:
  - name: tensorflow-cpu
    image: "gcr.io/agarwalrohit-sandbox/tensorflow-cpu:v1.8"
    command: ["python",  "/matmul.py", "/cpu:0", "200"]
  restartPolicy: Never
