apiVersion: v1
kind: Pod
metadata:
  name: gpu-verification
spec:
  containers:
    - name: gpu-verification
      image: "gcr.io/google_containers/busybox:1.24"
      command:
        - sh
        - -c
        - if [[ 1 -ne $(ls /dev/ | egrep '^nvidia[0-9]+$' | wc -l) ]]; then exit 1; else echo Success; fi
      resources:
        limits:
          nvidia.com/gpu: 1
